---
driver:
  name: vagrant

driver_config:
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 443, host: 8443}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[expensify::default]
    verifier:
      inspec_tests:
        - test/smoke/default/default_test.rb
  - name: app_a
    run_list:
      - recipe[expensify::app_a]
    verifier:
      inspec_tests:
      - test/smoke/default/app_a_test.rb
  - name: app_b
    run_list:
      - recipe[expensify::app_b]
    verifier:
      inspec_tests:
      - test/smoke/default/app_b_test.rb
  - name: lb
    run_list:
      - recipe[expensify::lb]
    verifier:
      inspec_tests:
      - test/smoke/default/lb_test.rb
  - name: nagios
    run_list:
      - recipe[expensify::nagios]
    verifier:
      inspec_tests:
      - test/smoke/default/nagios_test.rb
    data_bags_path: "test/smoke/data_bags/"
  - name: firewall_external
    run_list:
      - recipe[expensify::firewall_external]
    verifier:
      inspec_tests:
      - test/smoke/default/firewall_external_test.rb
  - name: firewall_internal_app
    run_list:
      - recipe[expensify::firewall_internal_app]
    verifier:
      inspec_tests:
      - test/smoke/default/firewall_internal_app_test.rb
